name: Auto Update Tapmad Playlist

on:
  

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Checkout Public Repo
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      # Clone Private Repo
      - name: Clone Private Repo
        run: |
          git clone https://${{ secrets.PRIVATE_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO }}.git private_repo

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Dependencies
      - name: Install Requests
        run: |
          pip install requests

      # Run Private Script
      - name: Run Script
        run: |
          python private_repo/tapmad_sm.py

      # Commit & Push Playlist
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add Tapmad_sm.m3u

          git commit -m "Auto Update Tapmad Playlist" || echo "No changes"

          git push
