name: Auto Update Tapmad Playlist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Public Repo Checkout
      - name: Checkout Public Repo
        uses: actions/checkout@v4

      # Private Repo Clone
      - name: Clone Private Repo
        run: |
          git clone https://${{ secrets.PRIVATE_TOKEN }}@github.com/sm-monirulislam/SM-Live-TV-Secret-Project-EXP.git private_repo

      # Python Setup
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install Dependencies
      - name: Install Requests
        run: |
          pip install requests

      # Run Private Script
      - name: Run Script
        run: |
          python private_repo/main.py

      # Push Generated Playlist
      - name: Commit & Push Playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add Tapmad_sm.m3u

          git commit -m "Auto Update Playlist" || echo "No changes"

          git push
